### ISSUE TITLE
Pronote did not return ICal token

### ISSUE THREAD

**Issue by GaPhi** [delphiki/hass-pronote#12]
En version 0.6.0:

```
2023-09-13 23:59:54.515 ERROR (MainThread) [custom_components.pronote.coordinator] Error getting data from pronote: Pronote did not return ICal token
2023-09-13 23:59:54.518 ERROR (MainThread) [custom_components.pronote.coordinator] Unexpected error fetching XXX XXX (via compte parent) data: Pronote did not return ICal token
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 293, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pronote/coordinator.py", line 214, in _async_update_data

    raise ex
  File "/config/custom_components/pronote/coordinator.py", line 191, in _async_update_data
    self.data['ical_url'] = await self.hass.async_add_executor_job(client.export_ical)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pronotepy/clients.py", line 470, in export_ical
    raise ICalExportError("Pronote did not return ICal token")
pronotepy.exceptions.ICalExportError: Pronote did not return ICal token
```

**Comment by GaPhi** [comment]
La suppression du compte et sa recréation n'y change rien.

Une tentative de retour en version 0.5.1 par l'interface HACS n'a pas permis de retrouver l'état opérationnel d'avant la mise à jour vers 0.6.0... Il semble que l'on reste en 0.6.0 malgré la sélection de la version 0.5.1.

**Comment by delphiki** [comment]
Hello @GaPhi,

Le souci est corrigé avec la version 0.6.2 :)

**Comment by GaPhi** [comment]
Je confirme. Merci !
