### ISSUE TITLE
Erreur quand infos non publiées

### ISSUE THREAD

**Issue by Tandonnet** [delphiki/hass-pronote#14]
Mon lycée ne publie pas de menus ou d'évaluations, donc l'intégration ne se charge pas. 
Erreur :
`Unexpected error fetching TANDONNET Samuel data: 'ListeJours'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 293, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pronote/coordinator.py", line 214, in _async_update_data
    raise ex
  File "/config/custom_components/pronote/coordinator.py", line 210, in _async_update_data
    self.data['menus'] = await self.hass.async_add_executor_job(client.menus, date.today(), date.today() + timedelta(days=7))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pronotepy/clients.py", line 646, in menus
    l_list = response["donneesSec"]["donnees"]["ListeJours"]["V"]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'ListeJours'`
Serait-il donc possible de simplement noter ces sensors comme indisponibles ou ajouter une option pour ne pas les charger pour éviter d'empêcher l'intégration de fonctionner?

**Comment by GaPhi** [comment]
idem #12

**Comment by Tandonnet** [comment]
Le problème est réglé en repassant sur la 0.5.1

**Comment by delphiki** [comment]
Hello @Tandonnet,

Le souci pour les menus devrait être corrigé avec la version 0.6.2

**Comment by Tandonnet** [comment]
Effectivement, tout fonctionne.
