### ISSUE TITLE
Erreurs / plus de maj avec 0.7.0 

### ISSUE THREAD

**Issue by vingerha** [delphiki/hass-pronote#22]
STP envoyer vos logs

**Comment by albattar29** [comment]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TypeError: object of type 'NoneType' has no len()
2023-09-20 08:36:24.008 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=(<table>  
{% set items = state_attr('sensor.pronote_hervo_merwan_averages','averages')%}
<tr> 
<td><h3>Cours<h3></td>
<td><h3>Average</td>
<td><h3>Class</td>
<td><h3>Max</td>
<td><h3>Min</td>
</tr> 
{% for i in range(0, items | count, 1) %}
<tr> 
 {% if items[i].average >= '14' %} 
 <td width="80&"><mark>{{ items[i].subject }}</mark> </td>  {% else %} <td><span>{{ items[i].subject }}</td>  
 {% endif %} 
   <td>{{ items[i].average }}</td>
   <td>{{ items[i].class }}</td>
   <td>{{ items[i].max }}</td>
   <td>{{ items[i].min }}</td>
{% endfor %}) renders=80>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2198, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 10, in top-level template code
TypeError: object of type 'NoneType' has no len()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TypeError: object of type 'NoneType' has no len()

**Comment by vingerha** [comment]
> Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info render_info._result = self.async_render( ^^^^^^^^^^^^^^^^^^ File 

C'est une erreur que dans la carte concernant Averages, il faut l'analyser/comparer avec d'autres utilisateur. Peut-être t'as pas encore des Averages?

**Comment by albattar29** [comment]
le log est long comme le bras,  j'ai plus ou moins la meme chose sur l'ensemble des entitées

**Comment by albattar29** [comment]
Unexpected error fetching ******* Louka (via compte parent) data: 'ListeTravauxAFaire'
09:10:44 – (ERREUR) Pronote (intégration personnalisée) - message survenu pour la première fois à 07:19:57 et apparu 179 fois.
Error getting data from pronote: 'ListeTravauxAFaire'
09:10:44 – (ERREUR) Pronote (intégration personnalisée) - message survenu pour la première fois à 07:19:57 et apparu 179 fois.
Error doing job: Task exception was never retrieved
09:09:57 – (ERREUR) components/scrape/sensor.py - message survenu pour la première fois à 07:29:57 et apparu 22 fois.
Error while processing template: Template<template=(<table> {% set items = state_attr('sensor.pronote_********_louka_homework','homework') %} {% for i in range(0, items | count, 1) %} {% if i == 0 %} <tr><td colspan="2"><b>{{ items[i].date.strftime("%A %d") }}</td></tr> {% endif %} {% if items[i].date > items[i-1].date %} <tr><td colspan=2><p><b>{{ items[i].date.strftime("%A %d") }}</p></td></tr> {% endif %} <tr> {%- if items[i].done == true -%} <td> <mark> {{ items[i].subject }}</mark></td> {% else %} <td> <span> {{ items[i].subject }}</span></td> {%- endif -%} <td>{{ items[i].description }}</td> <td></td> </tr> {% endfor %}) renders=190>
09:05:59 – (ERREUR) helpers/template.py - message survenu pour la première fois à 07:19:25 et apparu 542 fois.
Error getting ical_url from pronote: Pronote did not return ICal token
09:05:15 – (ERREUR) Pronote (intégration personnalisée) - message survenu pour la première fois à 07:19:58 et apparu 9 fois.

**Comment by albattar29** [comment]
2023-09-20 07:19:25.721 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({% set months = ["Janvier","Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"] %}

**Comment by vingerha** [comment]
Sauf le "Error getting ical_url from pronote: Pronote did not return ICal token" tous sont liées avec tes cartes, soit pas de données soit des erreurs dans leurs configuration.
L 'erreur ical est connu et on vera comment le faire disparaitre car tant des gens (comme moi) ont pas un calendrier dans pronote

Pour être transparent, j'aide ave l'intégration mais pas pour analyser des cartes car les gens changent/adapter leur code trops souvent ... c'est trops de travail.... pour les cartes, continue stp sur le forum

**Comment by GaPhi** [comment]
Un exemple (pas forcément avec toutes les infos disponibles) de cartes et automatisation en version 0.7.0, surement perfectibles également.

J'ai mutualisé le thème et amélioré la présentation suite aux premiers constats visibles sur le fonctionnement du lycée de mon fils ; cela reste donc nécessairement à personnaliser mais la base est peut-être un peu plus saine.
[Perso-0.7.0.zip](https://github.com/delphiki/hass-pronote/files/12672367/Perso-0.7.0.zip)

**Comment by vingerha** [comment]
merci mais c'est pas le bon endroit, j'ai ouvert ce post pour avoir des erreurs autour de MAJ

**Comment by Mika59940** [comment]
**Bonjour, j'ai la version 0.7.0 de l'intégration et voici l'erreur donnée après 24h de fonctionnement:**







2023-09-20 11:01:16.363 DEBUG (SyncWorker_1) [pronotepy.ent.generic_func] [ENT https://enthdf.fr] Logging in with xxxxxx
2023-09-20 11:01:16.502 DEBUG (SyncWorker_1) [pronotepy.ent.generic_func] [EduConnect https://educonnect.education.gouv.fr/idp/profile/SAML2/Unsolicited/SSO?execution=e1s1] Logging in with xxxxxx
2023-09-20 11:01:17.662 DEBUG (SyncWorker_1) [custom_components.pronote.coordinator] 'a'
2023-09-20 11:01:17.663 INFO (MainThread) [custom_components.pronote.coordinator] NO CLIENT FOR PRONOTE
2023-09-20 11:01:17.664 DEBUG (MainThread) [custom_components.pronote.coordinator] Finished fetching xxxxxx data in 1.301 seconds (success: True)
2023-09-20 11:01:17.665 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 235, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 392, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 473, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 797, in _async_generate_attributes
    name := (entry and entry.name) or self._friendly_name_internal()
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 750, in _friendly_name_internal
    name = self.name
           ^^^^^^^^^
  File "/config/custom_components/pronote/sensor.py", line 117, in name
    return f"{DOMAIN}_{self.coordinator.data['sensor_prefix']}"
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by delphiki** [comment]
@Mika59940 Peux-tu tester avec la dernière release 0.8.0 ?

**Comment by Mika59940** [comment]
Merci @delphiki, je viens de l'installer

**Comment by vingerha** [comment]
Closed, reopening one with 0.8.0
