### ISSUE TITLE
No device or entities

### ISSUE THREAD

**Issue by romsworld** [delphiki/hass-pronote#29]
Hi,

After add Pronote, I have the name of my son, but I don't have device or entities.
It's strange.
I use ENT Essone.

Perhaps it's -- in the name the problem ?

Thanks for your help,

2023-09-20 19:59:19.442 DEBUG (SyncWorker_2) [pronotepy.ent.generic_func] [ENT https://www.moncollege-ent.essonne.fr/auth/login] Logging in with prenom.nom
2023-09-20 19:59:20.621 ERROR (MainThread) [custom_components.pronote.coordinator] Error getting data from pronote: 'NoneType' object does not support item assignment
2023-09-20 19:59:20.624 ERROR (MainThread) [custom_components.pronote.coordinator] Unexpected error fetching NAME1--NAME2 Prénom (via compte parent) data: 'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pronote/coordinator.py", line 221, in _async_update_data
    raise ex
  File "/config/custom_components/pronote/coordinator.py", line 161, in _async_update_data
    self.data['account_type'] = data['account_type']
    ~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment
2023-09-20 19:59:20.634 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 229, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 431, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 834, in _async_write_ha_state
    name := (entry and entry.name) or self._friendly_name_internal()
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 766, in _friendly_name_internal
    name = self.name
           ^^^^^^^^^
  File "/config/custom_components/pronote/sensor.py", line 117, in name
    return f"{DOMAIN}_{self.coordinator.data['sensor_prefix']}"
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by delphiki** [comment]
Ce souci devrait être corrigé avec la version [0.8.](https://github.com/delphiki/hass-pronote/releases/tag/0.8.0)0
