### ISSUE TITLE
Erreurs avec 0.8.0

### ISSUE THREAD

**Issue by vingerha** [delphiki/hass-pronote#30]
```
Last logged: 06:58:47

Error adding entities for domain sensor with platform pronote
Error while setting up pronote platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1002, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 774, in _async_generate_attributes
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pronote/sensor.py", line 233, in extra_state_attributes
    'class_average': float(re.sub(',', '.', grade.average)),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

**Comment by vingerha** [comment]
```
Last logged: 06:59:03

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1131, in _async_registry_updated
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 774, in _async_generate_attributes
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pronote/sensor.py", line 233, in extra_state_attributes
    'class_average': float(re.sub(',', '.', grade.average)),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

**Comment by delphiki** [comment]
Oui, je pense qu'il va falloir tester unitairement tous les champs avant de faire des opérations dessus, car s'ils sont vides, ça plante

**Comment by vingerha** [comment]
Solution: 
```
'class_average': float(re.sub(',', '.', str(grade.average).replace('None','0,0'))),

**Comment by vingerha** [comment]
Plus simple (trial and error car je ne suis pas trops ajour avec python)
```
'class_average': str(grade.average).replace('.',','),

**Comment by vingerha** [comment]
je vais retirer mon PR ajouter ci-dessus et re-ajouter information/surveys, d'accord?

**Comment by vingerha** [comment]
Correction: il existe un autre PR.... je ne le refait pas ... je le laisse à @GaPhi

**Comment by vingerha** [comment]
Testé ton allternative dans 0.9.0 mais encore même soucis.
Seul choses qui marche 
```
'class_average': str(grade.average).replace('.',','),
```
Ja fait un PR ?
