### ISSUE TITLE
No devices or entries

### ISSUE THREAD

**Issue by MickaelDENIS** [delphiki/hass-pronote#34]
Bonjour,
lors de l'intégration j'ai cette erreur 
2023-09-25 16:54:09.174 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry DENIS Maïlys (via compte parent) for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 137, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

Je suis sur un HA sous docker en 2023.7.3 j'ai pris la dernière version de hass-pronote 0.8.1  
Une autre point comment mettre à jour les informations de connexion.
Merci de votre aide

**Comment by delphiki** [comment]
Hello,

Effectivement, la dernière version de l'intégration est compatible uniquement avec une version d'HA 2023.8+.
Ils ont changés des choses dans le Device registry.
Du coup il faut que tu mettes à jour ton HA si tu veux en profiter, sinon ça me ferait maintenir deux versions du code en parallèle, ça serait un peu chronophage :)

**Comment by MickaelDENIS** [comment]
Pas de problème, je vais faire l'update, merci

**Comment by MickaelDENIS** [comment]
Je confirme après  la mise à jour en 2023.9.3 je récupère bien les nouvelles entrées.
Merci de ton retour
Juste une amélioration possible serait de pouvoir changer la connexion sans devoir tout changer serait bien.
Merci
