### ISSUE TITLE
Erreur au chargement du profil

### ISSUE THREAD

**Issue by silversmarty** [delphiki/hass-pronote#36]
Bonjour,

la configuration de l'intégration se passe bien, mais aucun sensor n'est créé et le journal me remonte cette erreur :

```
Error unloading entry NOM Prénom (via compte parent) for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 544, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 138, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```
Est-ce que cette erreur est connue ? Comment la corriger ?

Merci beaucoup !
Paul

**Comment by MickaelDENIS** [comment]
Bonsoir, j'ai eu la même erreur, est-ce que ton home assistant est bien à jour , version mini 2023.8

**Comment by silversmarty** [comment]
HA : 2023.8.4 (donc à jour)
version de l'intégration : 0.8.1

**Comment by MickaelDENIS** [comment]
essaye de mettre la dernière version 2023.9.3 pour moi ça a fonctionné . sinon je laisserais delphiki te répondre.

**Comment by silversmarty** [comment]
En effet, ça a réglé le problème. Merci !!
