### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by GaPhi** [delphiki/hass-pronote#57]
Après la mise à jour en 0.13.3 (depuis une version bien plus ancienne), mes journaux sont remplis de :
```
2023-11-09 09:55:58.970 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/config/custom_components/portainer/entity.py", line 114, in _handle_coordinator_update
    self._data = self.coordinator.data[self.description.data_path][self._uid]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'fa766f4f21a00706f49e97954ec945b60165f600fab0861ff649927781da5405'
```

Une idée ?

**Comment by GaPhi** [comment]
A surveiller sur la durée (je ne clos pas encore) mais semble résolu avec 0.13.4

**Comment by GaPhi** [comment]
Plus d'erreur depuis 0.13.4
