### ISSUE TITLE
Erreur depuis deux jours avec la dernière version

### ISSUE THREAD

**Issue by maathiieus** [delphiki/hass-pronote#90]
Bonjour,

Depuis 2 jours l'intégration ne fonctionne plus correctement et en regardant les logs j'ai ceci comme erreur

> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
>     self.data = await self._async_update_data()
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/pronote/coordinator.py", line 107, in _async_update_data
>     client = await self.hass.async_add_executor_job(get_pronote_client, config_data)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/pronote/pronote_helper.py", line 14, in get_pronote_client
>     return get_client_from_qr_code(data)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/pronote/pronote_helper.py", line 89, in get_client_from_qr_code
>     return (pronotepy.ParentClient if data['account_type'] == 'parent' else pronotepy.Client).token_login(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pronotepy/clients.py", line 268, in token_login
>     return cls(
>            ^^^^
>   File "/usr/local/lib/python3.12/site-packages/pronotepy/clients.py", line 987, in __init__
>     super().__init__(
>   File "/usr/local/lib/python3.12/site-packages/pronotepy/clients.py", line 151, in __init__
>     self.logged_in = self._login()
>                      ^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pronotepy/clients.py", line 334, in _login
>     dec_no_alea = _enleverAlea(dec.decode())
>                                ^^^^^^^^^^^^

Je ne sais pas si il s'agit d'une modification au niveau du système pronote ou suite à une maj de HA

**Comment by delphiki** [comment]
Hello,

Est-ce que le problème est toujours présent avec la dernière version 1.15.3 ?
Quelle version de HA utilises-tu ?
