### ISSUE TITLE
Plus de connexion pronote

### ISSUE THREAD

**Issue by ManceauJulien** [delphiki/hass-pronote#94]
Bonjour. Mon intégration pronot a cessé de fonctionner.
Voici le journal :
Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.pronote.coordinator
Source: helpers/update_coordinator.py:379
intégration: Pronote (documentation, problèmes)
S'est produit pour la première fois: 22:06:09 (14 occurrences)
Dernier enregistrement: 22:15:01

Unexpected error fetching xxxxxxxxx (via compte parent) data
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pronotepy/pronoteAPI.py", line 325, in aes_decrypt
    return Padding.unpad(cipher.decrypt(data), 16)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/Crypto/Util/Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pronote/coordinator.py", line 113, in _async_update_data
    client = await self.hass.async_add_executor_job(get_pronote_client, config_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/pronote/pronote_helper.py", line 40, in get_pronote_client
    return get_client_from_qr_code(data)
  File "/config/custom_components/pronote/pronote_helper.py", line 129, in get_client_from_qr_code
    ).token_login(
      ~~~~~~~~~~~^
        pronote_url=qr_code_url,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        client_identifier=qr_code_client_identifier,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pronotepy/clients.py", line 268, in token_login
    return cls(
        pronote_url,
    ...<6 lines>...
        device_name=device_name,
    )
  File "/usr/local/lib/python3.13/site-packages/pronotepy/clients.py", line 987, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        pronote_url,
        ^^^^^^^^^^^^
    ...<7 lines>...
        device_name,
        ^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pronotepy/clients.py", line 151, in __init__
    self.logged_in = self._login()
                     ~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/pronotepy/clients.py", line 333, in _login
    dec = e.aes_decrypt(bytes.fromhex(challenge))
  File "/usr/local/lib/python3.13/site-packages/pronotepy/pronoteAPI.py", line 327, in aes_decrypt
    raise CryptoError(
        "Decryption failed while trying to un pad. (probably bad decryption key/iv)"
    )
pronotepy.exceptions.CryptoError: ('Decryption failed while trying to un pad. (probably bad decryption key/iv)', 'exception happened during login -> probably bad username/password')

**Comment by ManceauJulien** [comment]
Problème finalement résolu en désinstallant et réinstallant l'intégration.
Bonne journée

**Comment by papaeng89** [comment]
Bonjour et meilleurs voeux à tous,
J'ai la même erreur même en désinstallant et réinstallant l'intégration l'erreur est toujours présente.

Bonne fin de journée

**Comment by papaeng89** [comment]
Comme le dit skillix : 
J'ai eu le soucis également, mais je viens de trouver le PB, Tu dois probablement comme moi passer par le QRCODE, mais le format à changer, il y a un champs en plus dans le JSON, il faut supprimer : "avecPageConnexion":false, au tout début.

Supprime cette partie et ca fonctionne
Source : https://github.com/delphiki/hass-pronote/issues/93#issuecomment-2574622603
